## attribute of numpy array:

In [ ]:
#dimenssion:

In [3]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
a.ndim

1

In [4]:
b=np.array([[1,2],[3,4]])
b.ndim

2

In [ ]:
#shape:

In [5]:
a1=np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [6]:
a1.shape

(5,)

In [7]:
b1=np.array([[1,2],[3,4]])
b1

array([[1, 2],
       [3, 4]])

In [8]:
b1.shape

(2, 2)

In [9]:
c1=np.zeros((2,3,4))
c1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
c1.shape

(2, 3, 4)

In [11]:
c2=np.array([2,3,4])
c2

array([2, 3, 4])

In [12]:
c2.shape

(3,)

In [13]:
#size:

In [14]:
c1=np.zeros((2,3,4))
c1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
c1.size

24

In [16]:
b1=np.array([[1,2],[3,4]])
b1

array([[1, 2],
       [3, 4]])

In [17]:
b1.size

4

In [18]:
#dtype:

In [19]:
b1=np.array([[1,2],[3,4]])
b1.dtype

dtype('int32')

In [20]:
c1=np.zeros((2,3,4))
c1.dtype

dtype('float64')

In [21]:
#itemsize:

In [22]:
c1=np.zeros((2,3,4))
c1.itemsize

8

In [23]:
b1=np.array([[1,2],[3,4]])
b1.itemsize

4

In [24]:
#numerical data types:

In [25]:
a2=np.zeros(5)
a2.dtype

dtype('float64')

In [26]:
b2=np.zeros(6,dtype="int")
b2

array([0, 0, 0, 0, 0, 0])

In [27]:
b2=np.zeros(6,dtype=np.int8)
b2

array([0, 0, 0, 0, 0, 0], dtype=int8)

In [28]:
#using the datatype as function:

In [29]:
x=np.float32([1,2,3,4])
x

array([1., 2., 3., 4.], dtype=float32)

In [30]:
x.dtype

dtype('float32')

In [31]:
 #datatype can be reffered by character code:

In [32]:
y=np.array([5,6,7,8],dtype='f')
y

array([5., 6., 7., 8.], dtype=float32)

In [ ]:
#changining the data type of array using .astype():

In [33]:
 x=np.float32([1,2,3,4])
x

array([1., 2., 3., 4.], dtype=float32)

In [34]:
x.astype(int)

array([1, 2, 3, 4])

In [36]:
p=np.zeros(3)
p

array([0., 0., 0.])

In [37]:
p.astype(int)

array([0, 0, 0])

In [39]:
np.float64(p)

array([0., 0., 0.])

In [40]:
#indexing in numpy:

In [41]:
#1d array indexing:

In [42]:
m=np.array([1,2,3,4,5])
m

array([1, 2, 3, 4, 5])

In [43]:
m[3]

4

In [44]:
m[-2]

4

In [45]:
#2d array indexing:

In [46]:
n=np.array([[1,2],[3,4],[5,6]])
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
n[0][1]

2

In [49]:
n[-3][-1]

2

In [50]:
#3d array indexing:

In [51]:
r=[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]
s=np.array(r)
s

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [52]:
s[0][0][1]

2

In [53]:
s[-2][-3][-3]

1

In [54]:
s[0][1][0]

4

In [55]:
#slicing operation in numpy:

In [56]:
#1d array slicing:

In [57]:
m=np.array([1,2,3,4,5])
m

array([1, 2, 3, 4, 5])

In [58]:
m[0::2]

array([1, 3, 5])

In [59]:
m[:]

array([1, 2, 3, 4, 5])

In [60]:
m[1:4:]

array([2, 3, 4])

In [61]:
#2d array slicing:

In [62]:
n=np.array([[1,2],[3,4],[5,6]])
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
n[1:,1:]

array([[4],
       [6]])

In [64]:
n[2:,1:]

array([[6]])

In [65]:
#3d array slicing:

In [66]:
r=[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]
s=np.array(r)
s

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
s[:,:,1]

array([[ 2,  5,  8],
       [11, 14, 17]])

In [68]:
s[:,:,0]

array([[ 1,  4,  7],
       [10, 13, 16]])

In [69]:
s[:,1:,::2]

array([[[ 4,  6],
        [ 7,  9]],

       [[13, 15],
        [16, 18]]])

In [70]:
#advance indexing:

In [71]:
m1=np.arange(1,10)
m1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
index=np.array([1,4,5])
m1[index]

array([2, 5, 6])

In [73]:
m1[[2,5,6]]

array([3, 6, 7])

In [74]:
m1[[1,4,5]]

array([2, 5, 6])

In [75]:
r1=np.array([[1,2,3],[4,5,6],[7,8,9]])
r1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
r1[[0,2],[2,0]]

array([3, 7])

In [77]:
r1[[1,1,2],[0,2,1]]

array([4, 6, 8])

In [78]:
#boolean indexing:

In [79]:
j=np.array([[1,-2,3],[-5,-3,4]])
j

array([[ 1, -2,  3],
       [-5, -3,  4]])

In [80]:
j[j<0]

array([-2, -5, -3])

In [81]:
j[j>0]

array([1, 3, 4])

In [82]:
j[j>0]*2

array([2, 6, 8])

In [1]:
#arithmetic operation:

In [4]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [5]:
a+2

array([3, 4, 5, 6])

In [6]:
a*3

array([ 3,  6,  9, 12])

In [7]:
a-1

array([0, 1, 2, 3])

In [8]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [9]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [10]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [11]:
b1=np.array([[1,2],[3,4]])
b1

array([[1, 2],
       [3, 4]])

In [12]:
b1+2

array([[3, 4],
       [5, 6]])

In [14]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [15]:
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [24]:
b.shape

(4,)

In [ ]:
#adding two 1d array:

In [16]:
a+b

array([11, 22, 33, 44])

In [18]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[7,8,9],[10,11,12]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c.shape

(2, 3)

In [19]:
d

array([[ 7,  8,  9],
       [10, 11, 12]])

In [20]:
c+d

array([[ 8, 10, 12],
       [14, 16, 18]])

In [21]:
c*d

array([[ 7, 16, 27],
       [40, 55, 72]])

In [23]:
np.subtract(c,d)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [26]:
#broadcasting:

In [32]:
e=np.array([[1,2],[3,4],[5,6]])
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
e.shape

(3, 2)

In [34]:
f=np.array([10,20])
f

array([10, 20])

In [35]:
f.shape

(2,)

In [36]:
e+f

array([[11, 22],
       [13, 24],
       [15, 26]])

In [37]:
g=np.array([10,20,30])
g

array([10, 20, 30])

In [38]:
g.shape

(3,)

In [39]:
e+g

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [40]:
h=np.array([[1,2],[7,8]])
h

array([[1, 2],
       [7, 8]])

In [41]:
h.shape

(2, 2)

In [42]:
e+h

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [43]:
a=np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [44]:
a.shape

(3, 1)

In [45]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [46]:
b.shape

(3,)

In [47]:
a+b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [48]:
#array manupulation:

In [49]:
#reshape:

In [50]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a.shape

(10,)

In [52]:
b=np.reshape(a,(5,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
c=np.reshape(a,(5,2),order="F")
c

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [55]:
#resize:

In [56]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 4, 0]])

In [62]:
a.resize((5,2))
a

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [1]:
#flatten:

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
a.flatten(order="F")

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [7]:
a.flatten(order="k")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
#ravel():

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.flatten(a)

AttributeError: module 'numpy' has no attribute 'flatten'

In [14]:
#transpose:

In [15]:
#2d array--

In [16]:
b=np.arange(1,11).reshape(5,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
np.transpose(b)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [19]:
b.shape

(5, 2)

In [20]:
np.transpose(b).shape

(2, 5)

In [26]:
np.transpose(b,axes=(0,1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
b.transpose(1,0)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [21]:
#3d array--

In [22]:
c=np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [23]:
np.transpose(c)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [28]:
#swapaxes:

In [29]:
b=np.arange(1,11).reshape(5,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
np.swapaxes(b,0,1)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [33]:
c=np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [35]:
np.swapaxes(c,1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [36]:
np.swapaxes(c,0,2)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [37]:
c.swapaxes(1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [1]:
#matrix:

In [2]:
#matrix implementation using numpy array:

In [4]:
import numpy as np

In [5]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [6]:
a+b

array([[11, 22],
       [33, 44]])

In [7]:
a*b

array([[ 10,  40],
       [ 90, 160]])

In [8]:
a.dot(b)

array([[ 70, 100],
       [150, 220]])

In [9]:
#matrix implemantation using matrix class:

In [ ]:
#from list:

In [10]:
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[10,20],[30,40]])


In [11]:
a

matrix([[1, 2],
        [3, 4]])

In [12]:
b

matrix([[10, 20],
        [30, 40]])

In [ ]:
#from string:

In [13]:
a=np.matrix("1 2;3 4")
b=np.matrix("10 20;30 40")
print(a)
print(b)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [14]:
a+b

matrix([[11, 22],
        [33, 44]])

In [15]:
a*b

matrix([[ 70, 100],
        [150, 220]])

In [16]:
a.T

matrix([[1, 3],
        [2, 4]])

In [17]:
b.T

matrix([[10, 30],
        [20, 40]])

In [18]:
#inverse:

In [19]:
a=np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [20]:
b=np.linalg.inv(a)
b

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [21]:
a.dot(b)

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])

In [22]:
#power:

In [23]:
a=np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [24]:
np.linalg.matrix_power(a,2)

matrix([[ 7, 10],
        [15, 22]])

In [26]:
np.linalg.matrix_power(a,0)

matrix([[1, 0],
        [0, 1]])

In [27]:
np.linalg.matrix_power(a,-2)

matrix([[ 5.5 , -2.5 ],
        [-3.75,  1.75]])

In [29]:
b=np.linalg.inv(a)
b

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [30]:
np.linalg.matrix_power(b,2)

matrix([[ 5.5 , -2.5 ],
        [-3.75,  1.75]])

In [1]:
#linear equation:

In [4]:
import numpy as np

In [ ]:
#using 3 varriable:
#6x+2y-5z=13,3x+3y-2z=13,7x+5y-3z=26(using n-d array)

In [39]:
x=np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
x

array([[ 6,  2, -5],
       [ 3,  3, -2],
       [ 7,  5, -3]])

In [40]:
y=np.array([13,13,26])
y

array([13, 13, 26])

In [41]:
np.linalg.solve(x,y)

array([2., 3., 1.])

In [2]:
#using 2 varriable:
3x+y=9,x+2y=8(using matrix)

In [5]:
a=np.matrix([[3,1],[1,2]])
b=np.matrix([9,8])
np.linalg.solve(a,b.T)

matrix([[2.],
        [3.]])

In [43]:
#determinate:

In [44]:
a=np.matrix([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [45]:
np.linalg.det(a)

-2.0000000000000004

In [46]:
round(np.linalg.det(a))

-2.0

In [47]:
b=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
np.linalg.det(b)

-9.51619735392994e-16

In [49]:
round(np.linalg.det(b))

-0.0